# SHELL
shell /usr/bin/bash
shell_integration disabled

# Initial kitty size
remember_window_size no
initial_window_width 1250
initial_window_height 600

# MOD KEY
kitty_mod ctrl+shift

# MAPPED KEYS
map F1 new_window_with_cwd

# Bell sound
enable_audio_bell no

# TRANSPARENCY
#background_opacity 0.8
#background_blur 1

# WINDOWS
window_margin_width 2
window_padding_width 5
single_window_margin_width -1
single_window_padding_width -1

# WINDOW BORDER
# active_border_color #98971a
# inactive_border_color #a89984
window_border_width 1.5pt
draw_window_borders_for_single_window yes

# LAYOUT
enabled_layouts tall,*
confirm_os_window_close 0

# TAB LOOK
tab_bar_style powerline
#tab_powerline_style slanted
tab_activity_symbol '* '

# BEGIN_KITTY_THEME
# Gruvbox Light
include current-theme.conf
# END_KITTY_THEME

# foreground меняет оттенок всего; красит текст стандартного цвета
#foreground #dddddd
#background #000000

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 11
