#!/bin/sh

# Usage: git-radar <time> <commits> <clear-fetch>
# Periodically printout git log.
#
# <time>        - integer, print git log after <time> seconds.
# <commits>     - integer, print specified number of commits.
# <clear-fetch> - integer, clear console and fetch from all remotes
#                          after <clear-fetch> iterations.

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

time_arg=${1:-1200}
commits_arg=${2:-15}
clear_fetch_arg=${3:-10}

git_radar(){

    sec=$1
    arg_n=$2
    counter=0
    counter_max=$3

    #clear
    git fetch --all -v
    while true; do

        if [ $counter -eq $counter_max ]; then
            clear
            git fetch --all -v
            counter=0
        fi

        git lg -n $arg_n
        counter=$((counter + 1))

        printf "\nPress ${YELLOW}'q'${NC} to exit: "
        if read -t $sec -n 1 key; then

            case "$key" in
                q|Q)
                    # \033[1A cursor 1 line up
                    # \r return carriage
                    printf "\033[1A\r"
                    break
                    ;;
                *)
                    continue
                    ;;
            esac
        fi
    done
}

if [ $# -lt 3 ]; then
    printf "${YELLOW}Warning:${NC} Not enough arguments, using defaults where possible.\n"
    printf "${YELLOW}Arguments:${NC} git-radar $time_arg $commits_arg $clear_fetch_arg\n\n"
fi

git_radar $time_arg $commits_arg $clear_fetch_arg
